services:
  smiirl:
    build: .
    container_name: smiirl
    environment:
      - TZ=Europe/Vienna
    ports:
      - "80:80"
    volumes:
      - smiirl-state:/data
    restart: unless-stopped

volumes:
  smiirl-state:
